- block:
  - name: homebrew microsoft/tool
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items: "{{ packages }}"

  - name: homebrew cask microsoft/tool
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    homebrew_cask:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items: "{{ cask_packages }}"
  tags:
    - microsoft
