#!/bin/sh

# 1 initial setting
if [ $# -eq 1 ]; then
    if [ $1 = "-h" -o $1 = "help" ]; then
        echo "help"
        ## help description
        exit 0
    fi
  # exit 1
fi

# 2 common
## GNU Emacs
[ ! -e $HOME/.emacs.d ] && which emacs > /dev/null && ln -sf `pwd`/common/.emacs.d/ $HOME/

## vim
[ ! -e $HOME/.vimrc ] && which vim > /dev/null && ln -sf  `pwd`/common/.vimrc $HOME/.vimrc

# 3 OS (.bash_profile)
## 3.1 Linux
if [ `uname` = "Linux" ]; then
    ln -sf `pwd`/linux/.bash_profile $HOME/.bash_profile
    echo "Linux"

## 3.2 Mac OS X
elif [ `uname` = "Darwin" ]; then
    pwd
    echo "Mac OS X"
fi

# 4. reflect configuration
exec $SHELL -l
