#!/bin/bash
##################################################
# @Author: urchin-hat
# @Update: date 2019/02/15
# @using:
#    $ bash uninstall
#    $ ./uninstall
##################################################
read -p "Erase dotfiles and return to the initial state. ok? (y/N): " yn
if [ ${yn} != "y" ]; then exit; fi

unlink $HOME/.my_config
unlink $HOME/.bash_profile
unlink $HOME/.emacs.d
unlink $HOME/.vimrc
unlink $HOME/.inputrc

rm `pwd`/config/my_conf
rm `pwd`/config/user_info
rm `pwd`/.emacs.d/init.el

exec $SHELL -l
