#!/bin/sh

# install brew command
if !(type "brew" > /dev/null 2>&1); then
    echo "install brew..." && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install ansible
fi

echo "hello"
