- block:
  - name: homebrew cask google/tool install
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    homebrew_cask:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items: "{{ packages }}"
  tags:
    - google
